name: terraform

on:
  push:
    branches:
      master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TERRAFORM_PRE_RUN: |
    # Install latest Azure CLI
    curl -skL https://aka.ms/InstallAzureCLIDeb | bash  

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: terraform apply

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo $PATH
          whereis az
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./terraform